version: '3.8'  # You can adjust the version as per your Docker Engine version

services:
  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server:6.0-ubi8
    ports:
      - "27017:27017"